blog/urls.py
from django.urls import path
from blog.views import PostView,PostDetail,PostCreate,PostUpdate,PostDelete,likeView,CommentView,add_comment_to_post
app_name = 'blog'
urlpatterns = [
	path('',PostView.as_view(), name = 'post-list'),
	path('detail/<int:pk>/',PostDetail.as_view(), name = 'post-detail'),
	path('create/',PostCreate.as_view(), name = 'post-create'),
	path('update/<int:pk>/',PostUpdate.as_view(), name = 'post-update'),
	path('delete/<int:pk>/',PostDelete.as_view(), name = 'post-delete'),
	path('ajax/likes/',likeView, name = 'like'),
	path('comment/',CommentView.as_view(),name ='comment'),
	path('detail/<int:pk>/comment/',add_comment_to_post,name = 'post-comment'),
	]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/',include('registration.backends.default.urls')),
    path('accounts/profile/',RedirectView.as_view(url ='/blog'))
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length = 100)
	body = models.TextField()
	created_date = models.DateTimeField(default = timezone.now)
	author = models.ForeignKey(get_user_model(),on_delete = models.CASCADE,null = True)
	img = models.ImageField(upload_to='',null = True)
	likes = models.IntegerField(null = True,default = 0)
	
	def __str__(self):
		return self.title

class Comment(models.Model):
	post = models.ForeignKey(Post,on_delete = models.CASCADE,related_name = "comments")
	text = models.TextField()
	timestamp = models.DateTimeField(default = timezone.now)

	def __str__(self):
		return self.text

blog/forms.py
from django import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['text']

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from blog.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from blog.forms import CommentForm
from django.views.generic.edit import FormView




# Create your views here.
class PostView(LoginRequiredMixin,ListView):
	model = Post

class PostDetail(LoginRequiredMixin,DetailView):
	model = Post

class PostCreate(LoginRequiredMixin,CreateView):
	model = Post
	fields = ['title','body','created_date','img']
	success_url = '/blog/'
	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


class PostUpdate(LoginRequiredMixin,UpdateView):
	model = Post
	fields = ['title','body','created_date','img']
	success_url = '/blog/'

class PostDelete(LoginRequiredMixin,DeleteView):
	model = Post
	fields = ['title','body','created_date','author','img']
	success_url = '/blog/'
def likeView(request):
	if request.method == 'GET':
		i = request.GET.get('i',None)
		p = Post.objects.get(id= i)
		p.likes = p.likes + 1
		p.save()
		data = {'i':p.likes}
	return JsonResponse(data)

class CommentView(FormView):
	form_class = CommentForm
	template_name = 'blog/comment.html'
	success_url = '/blog/'

	def form_valid(self,form):
		form.save()
		return super(CommentView,self).form_valid(form)


def add_comment_to_post(request,pk):
	post = get_object_or_404(Post,pk = pk)
	if request.method =='POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit = False)
			comment.post = post
			comment.save()
			return redirect('blog:post-detail',pk = post.pk)
	else:
		form = CommentForm()
	return render(request,'blog/comment.html',{'form':form})

blog/templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
	<title>Blog</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{%static 'css/style.css' %}">
	<script src="{%static 'js/script.js' %}" type="text/javascript"></script> 
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <a class="navbar-brand" href="#">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:post-list' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:post-create' %}">Post</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      {% if user.is_authenticated %}
      <b>{{request.user}}</b>&nbsp;<a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'auth_logout' %}">Logout</a>
      {% else %}
      <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'auth_login' %}">Login</a>
      <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'registration_register' %}">Register</a>
      {% endif %}
    </form>
  </div>
</nav>
<div class="container">
{% block content %}
{% endblock %}
</div>
</body>
</html>