blog/urls.py
from django.urls import path
from blog.views import PostView,PostDetail,PostCreate,PostUpdate,PostDelete,likeView,CommentView,add_comment_to_post
app_name = 'blog'
urlpatterns = [
	path('',PostView.as_view(), name = 'post-list'),
	path('detail/<int:pk>/',PostDetail.as_view(), name = 'post-detail'),
	path('create/',PostCreate.as_view(), name = 'post-create'),
	path('update/<int:pk>/',PostUpdate.as_view(), name = 'post-update'),
	path('delete/<int:pk>/',PostDelete.as_view(), name = 'post-delete'),
	path('ajax/likes/',likeView, name = 'like'),
	path('comment/',CommentView.as_view(),name ='comment'),
	path('detail/<int:pk>/comment/',add_comment_to_post,name = 'post-comment'),
	]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/',include('registration.backends.default.urls')),
    path('accounts/profile/',RedirectView.as_view(url ='/blog'))
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length = 100)
	body = models.TextField()
	created_date = models.DateTimeField(default = timezone.now)
	author = models.ForeignKey(get_user_model(),on_delete = models.CASCADE,null = True)
	img = models.ImageField(upload_to='',null = True)
	likes = models.IntegerField(null = True,default = 0)
	
	def __str__(self):
		return self.title

class Comment(models.Model):
	post = models.ForeignKey(Post,on_delete = models.CASCADE,related_name = "comments")
	text = models.TextField()
	timestamp = models.DateTimeField(default = timezone.now)

	def __str__(self):
		return self.text

blog/forms.py
from django import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['text']

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from blog.models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from blog.forms import CommentForm
from django.views.generic.edit import FormView




# Create your views here.
class PostView(LoginRequiredMixin,ListView):
	model = Post

class PostDetail(LoginRequiredMixin,DetailView):
	model = Post

class PostCreate(LoginRequiredMixin,CreateView):
	model = Post
	fields = ['title','body','created_date','img']
	success_url = '/blog/'
	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


class PostUpdate(LoginRequiredMixin,UpdateView):
	model = Post
	fields = ['title','body','created_date','img']
	success_url = '/blog/'

class PostDelete(LoginRequiredMixin,DeleteView):
	model = Post
	fields = ['title','body','created_date','author','img']
	success_url = '/blog/'
def likeView(request):
	if request.method == 'GET':
		i = request.GET.get('i',None)
		p = Post.objects.get(id= i)
		p.likes = p.likes + 1
		p.save()
		data = {'i':p.likes}
	return JsonResponse(data)

class CommentView(FormView):
	form_class = CommentForm
	template_name = 'blog/comment.html'
	success_url = '/blog/'

	def form_valid(self,form):
		form.save()
		return super(CommentView,self).form_valid(form)


def add_comment_to_post(request,pk):
	post = get_object_or_404(Post,pk = pk)
	if request.method =='POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit = False)
			comment.post = post
			comment.save()
			return redirect('blog:post-detail',pk = post.pk)
	else:
		form = CommentForm()
	return render(request,'blog/comment.html',{'form':form})

blog/templates/blog/comment.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<form method="post"  class="uniForm" enctype="multipart/form-data">{%csrf_token%}
	<div class="col-6">
	{{form|crispy}}
	<input class="btn btn-primary" type="submit" name="Save">
	</div>	
</form>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">{%csrf_token%}
	<p>Delete{{object}}?</p>
	<input type="submit" name="Confirm">
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
{{object.title}}<br>
<h3 id=h3id>{{object.title}}</h3><br>
<p class="bclass">{{object.body}}</p><br><br>

<button type="button" class="btn btn-success btn-sm" onclick="onClick()">Like</button>
<br>


<p id="btext">published by {{object.author}} on {{object.created_date}}</p><br><br>
<p id="like">{{object.likes}}</p>
<input id="likes_id" type="hidden" name="name" value="{{object.id}}">
<a type="button" class="btn btn-outline-warning" href="{% url 'blog:post-update' object.id %}">Update</a>
<a type="button" class="btn btn-outline-danger" href="{% url 'blog:post-delete' object.id %}">Delete</a>
<br><hr>

<a class="btn btn-primary btn-sm" href="{% url 'blog:post-comment' object.id %}" role="button">Comment</a>
<br><br>


{% for i in post.comments.all %}
<b>{{i.text}}</b><br>
{{i.timestamp}}<br>
<hr>
{% empty %}
No comments
{% endfor %}

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block content %}
<form method="post"  class="uniForm" enctype="multipart/form-data">{%csrf_token%}
	<div class="col-6">
	{{form|crispy}}
	<input class="btn btn-primary" type="submit" name="Save">
	</div>
</form>
{% endblock %}

blog/templates/blog/post_list.html
{%extends 'base.html' %}
{% block content %}

<div class="row">
{% for i in object_list %}
<div class="col-md-6">
<a id="h3id" href="{% url 'blog:post-detail' i.id %}">{{i.title}}</a><br><br>
{% if i.img %}
<img src="{{i.img.url}}"  height="300" width="300">
{% endif %}
<br>
Comments: {{ i.comments.count }}
<br><br>
</div>
{% endfor %}
</div>
{% endblock %}